openapi: 3.0.1

info:
  title: Winding Tree aggregator
  description: "This is the interface documentation for the REST api interface with the Winding Tree Aggregator"
  contact:
    email: mathieu@windingtree.com
  license:
    name: Apache License
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: /admin/v1
    description: Administration server

tags:
  - name: hotels
    description: Operations with hotels

paths:
  /hotels/add:
    post:
      tags:
        - hotels
      summary: Add hotel
      operationId: addHotels
      requestBody:
        description: Add hotel
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hotel"
        required: true
      responses:
        200:
          description: Hotel added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HotelAddResult"
        400:
          description: The sent request is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - orgid_auth:
            - admin
        - orgid_token: []
      x-codegen-request-body-name: body

  /hotels/addBulk:
    post:
      tags:
        - hotels
      summary: Add multiple hotels at ones
      operationId: addHotelsBulk
      requestBody:
        description: Array of hotels
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hotels"
        required: true
      responses:
        200:
          description: Hotel added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HotelAddResults"
        400:
          description: The sent request is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - orgid_auth:
            - admin
        - orgid_token: []
      x-codegen-request-body-name: body

  /hotels/{hotelId}/getById:
    get:
      tags:
        - hotels
      parameters:
        - name: hotelId
          in: path
          description: Hotel Id
          required: true
          schema:
            $ref: '#components/schemas/MongoId'
      summary: Get hotel by Id
      operationId: getHotelById
      responses:
        200:
          description: The hotel details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        400:
          description: The sent request is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - orgid_auth:
            - admin
        - orgid_token: []
  
  /hotels/{hotelId}/updateById:
    post:
      tags:
        - hotels
      parameters:
        - name: hotelId
          in: path
          description: Hotel Id
          required: true
          schema:
            $ref: '#components/schemas/MongoId'
      summary: Update hotel by Id
      operationId: updateHotelById
      requestBody:
        description: Update the hotel
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hotel"
        required: true
      responses:
        200:
          description: OK
          content:
            text/plain:
              type: string
              example: "OK"
        400:
          description: The sent request is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - orgid_auth:
            - admin
        - orgid_token: []


  /hotels/{hotelId}/removeById:
    delete:
      tags:
        - hotels
      parameters:
        - name: hotelId
          in: path
          description: Hotel Id
          required: true
          schema:
            $ref: '#components/schemas/MongoId'
      summary: Remove hotel by Id
      operationId: removeHotelById
      responses:
        200:
          description: OK
          content:
            text/plain:
              type: string
              example: "OK"
        400:
          description: The sent request is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - orgid_auth:
            - admin
        - orgid_token: []

  /hotels/search:
    post:
      tags: 
        - hotels
      summary: Search for hotels
      operationId: hotelsSearch
      requestBody:
        description: Search for hotels around matching input criteria
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HotelsSearchCriteria" 
            examples:
              polygonSearch:
                summary: Search within polygon boundary
                value:
                  {
                    "polygon": [
                      [
                        24.8963928,
                        60.1749466
                      ],
                      [
                        24.9700356,
                        60.1763126
                      ],
                      [
                        24.9720097,
                        60.1475721
                      ],
                      [
                        24.8987961,
                        60.1442394
                      ],
                      [
                        24.896307,
                        60.1748612
                      ]
                    ],
                    "sort": {
                      "provider": "asc"
                    },
                    "skip": 10,
                    "limit": 10
                  }
              locationSearch:
                summary: Search by location
                value:
                  {
                    "point": {
                      "longitude": 18.05437602,
                      "latitude": 59.33309777,
                      "radius": 50
                    },
                    "sort": {
                      "provider": "asc"
                    },
                    "skip": 10,
                    "limit": 10
                  }           
      responses:
        200:
          description: The hotel details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelSearchResult'
        400:
          description: The sent request is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - orgid_auth:
            - admin
        - orgid_token: []
      x-codegen-request-body-name: body

components:
  schemas:

    MongoId:
      description: Unique Id used in the MongoDB
      type: string
      example: "5e7a676620778a23098581cb"

    Hotel:
      description: Hotel
      type: object
      required: 
        - provider
        - ref
        - longitude
        - latitude
        - currency
      properties:
        provider:
          description: Hotel provider
          type: string
          example: "EREVMAX"
        ref:
          description: Hotel reference
          type: string
          example: "32788"
        longitude:
          description: Longitude
          type: number
          example: 18.05437602
        latitude:
          description: Latitude
          type: number
          example: 59.33309777
        currency: 
          description: The ISO4217 currency code
          type: string
          pattern: "^[A-Z]{3}$"
          minLength: 3
          maxLength: 3
          example: "EUR"

    Hotels:
      description: List of hotels
      type: array
      items:
        $ref: '#/components/schemas/Hotel'
    
    HotelsSearchCriteria:
      description: A search criteria for hotels search around coordinates
      type: object
      properties:
        polygon:
          description: Search within polygon boundary
          type: array
          items: 
            type: number           
        point:
          description: Search by location
          type: object
          required:
            - longitude
            - longitude
            - radius
          properties: 
            longitude:
              description: A longitude coordinate
              type: number
            latitude:
              description: A latitude coordinate
              type: number
            radius:
              description: A radius for search around in miles
              type: number
        sort:
          $ref: '#/components/schemas/SortingCriteria'
        skip:
          description: A count of records to skip in result
          type: number
          example: 
            10
        limit:
          description: A limit of records in responses
          type: string
    
    HotelAddResult:
      description: Hotel addition result
      type: object
      properties:
        id: 
          description: Id of the added hotel in the database
          type: string
          pattern: /^[a-f0-9]{24}$/i
          example: 507f1f77bcf86cd799439011

    HotelSearchResult:
      description: Response object for hotels search
      type: object
      required:
        - records
        - total
        - sort
        - skip
        - limit
      properties:
        records:
          type: array
          items:
            $ref: '#/components/schemas/Hotel'
        total:
          description: Total number of records
          type: number
          example: 5
        sort:
          $ref: '#/components/schemas/SortingCriteria'
        skip:
          description: A count of records to skip in result
          type: number
          example: 10
        limit:
          description: A limit of records in responses
          type: string
          example: 10
    
    HotelAddResults:
      description: List of hotel search results
      type: array
      items: 
        $ref: '#/components/schemas/HotelAddResult'
    
    SortingCriteria:
      description: Sorting criteria
      type: object
                
    Error:
      description: An error returned by Simard
      type: object
      properties:
        message:
          description: Information related to the error
          type: string
          example: "Invalid Input"

  # Defines the security schemes
  securitySchemes:
    orgid_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://staging.api.simard.io/oauth/authorize

    orgid_token:
      type: apiKey
      name: orgid_token
      in: header
