name: Automated Intagration Tests

on:
  pull_request:
    types: [assigned, unassigned]
    branches:
      - develop

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: 4.2

      - name: Start Redis
        uses: superchargejs/redis-github-action@master
        with:
          redis-version: 5

      # - name: Start Elastic Search
      #   uses: getong/elasticsearch-action@v1.2
      #   with:
      #     elasticsearch version: '7.6.1'
      #     host port: 9200
      #     container port: 9200
      #     host node port: 9300
      #     node port: 9300
      #     discovery type: 'single-node'

      - name: Run test suite
        run: |
          npm run test:newman
        env:
          AF_API_KEY: ${{ secrets.AF_API_KEY }}
          AF_COMISSION: 0
          AF_SENDER_NAME: Test
          AF_SENDER_PSEUDOCITY: PARMM211L
          AF_SENDER_IATA_NUMBER: 12345675
          AF_SENDER_AGENCY_ID: id
          AF_SENDER_AGENT_USER_ID: 1234
          AF_PARTICIPANT_ENABLED_SYSTEM_PARTICIPANT_SEQUENCE_NUMBER: 12
          AF_PARTICIPANT_ENABLED_SYSTEM_PARTICIPANT_NAME: MASHERY
          AF_PARTICIPANT_ENABLED_SYSTEM_PARTICIPANT_SYSTEM_ID: MAS
          AF_PARTICIPANT_RECIPENT_AIRLINE_ID: AF
          AF_PARTICIPANT_RECIPENT_NAME: AIRFRANCE
          MONGO_URI: mongodb://localhost:27017
          ELASTIC_URL: ${{ secrets.ELASTIC_SEARCH_URL }}
          REDIS_URL: redis://localhost:6379
          EREVMAX_RESERVATION_URL: https://ota-simulator.now.sh/api?ota=getOTAHotelReservation
          EREVMAX_AVAILABILITY_URL: https://ota-simulator.now.sh/api?ota=getOTAHotelAvailability
          SIMARD_ORGID: '0x5e6994f76764ceb42c476a2505065a6170178a24c03d81c9f372563830001171'
          GLIDER_ORGID: '0x71cd1781a3082f33d2521ac8290c9d4b3b3b116e4e8548a4914b71a1f7201da0'
          INFURA_ENDPOINT: wss://ropsten.infura.io/ws/v3
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          GLIDER_ADMIN_KEY: secondkey
          LIF_MIN_DEPOSIT: 0
          SIMARD_URL: https://staging.api.simard.io/api/v1

      - name: Assignee to Reviewer
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REVIEWERS: kostysh
