name: Automated Linting and Unit Tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '**'
  pull_request:
    types: [assigned, unassigned]
    branches:
      - develop

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      # - name: Code Linting
      #   run: npm run lint

      - name: Start Redis
        uses: superchargejs/redis-github-action@master
        with:
          redis-version: 5

      - name: Unit testing
        run: npm test
        env:
          GLIDER_ORGID: '0x71cd1781a3082f33d2521ac8290c9d4b3b3b116e4e8548a4914b71a1f7201da0'
          INFURA_ENDPOINT: wss://ropsten.infura.io/ws/v3
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          REDIS_URL: redis://localhost:6379 